apiVersion: v1
kind: Service
metadata:
  name: grpc-jaeger-demo-server
  labels:
    app: grpc-jaeger-demo-server
spec:
  ports:
    - name: grpc
      port: 5001
      protocol: TCP
      targetPort: 5001
  selector:
    app: grpc-jaeger-demo-server
